''' pyeps is a python function library for 
    creating numpy arrays using either normal cpu memeory
    or unified gpu memeory and converting between 
    numpy and eps arrays.
    It is intended to be used as support for the automatic
    python/eps wrapper functions generated by the eps compiler.

    Functions: 
          setup    Loads shared library
          Izeros1di : Creates numpy 1D 32  bit   integer numpy/eps array 
          Izeros2di : Creates numpy 2D 32  bit   integer numpy/eps array
          Fzeros1df : Creates numpy 32 bit float numpy/eps array
          Fzeros2df : Creates numpy 32 bit float numpyeps  array
          Fzeros    : Creates numpy 32 bit float numpy/eps array
          fzeros    : Creates 32 bit float numpy array
          Izeros    : Creates 32 bit int   numpy array
          Bytes     : Creates byte array 
          eps1di    : Convert 1D int numpy array to eps array
          num1di    : Convert 1D int eps   array to numpy array
          eps1dc    : Convert 1D char numpy array to eps array
          num1dc    : Convert 1D char eps   array to numpy array
          eps2di    : Convert 2D int numpy array to eps array
          num2di    : Convert 2D int eps   array to numpy array
          eps1df    : Convert 1D float numpy array to eps array
          num1df    : Convert 1D float eps array to numpy array
          eps2df    : Convert 2D float numpy array to eps array
          num2df    : Convert 2D float eps array to numpy array
          Dims1di   : Returns dimensions of eps array int 1D
          Dims2di   : Returns dimensions of eps array int 2D
          Dims1df   : Returns dimensions of eps array float 1D 
          Dims2df   : Returns dimensions of eps array float 2D

          The main features of the functions listed above are:

            1. Data is not copied, only pointers.
            2. The library works on both cpu and gpu using cpu memory 
               and unified memeory.
          
          The only requirement is that numpy arrays must be created with the
          Izeros and Fzeros functions. A numpy array created with f.ex np.zeros
          will not work.  The main reason for this is the distinction between
          cpu and gpu memory.  Data which is used by the gpu must be allocated
          using unified memory, which is done by Izeros and Fzeros.  It would
          be entirely possible to use normal numpy arrays created with f.ex.
          np.zeros, but then a full copy would have to be made of all functions
          argument to/from the gpu.  The overhead for this is very large, hence
          I use the approach with dedicated Izeros and Fzeros functions for
          creating numpy arrays.  Numpy arrays created in this way may be used
          to a limited extent as a normal numpy array, i.e reading/writing to
          the array from other numpy arrays.
          However, any operation involving slicing, reshape and similar
          which creates a non contigous memory is not allowed.

          Nvidia has made a similar library (pyCuda) which 
          uses the same approach,
          but is designed to interface with C.
          
          I have used different names for the num and eps functions,
          although they are identical. I will keep this until
          I am sure this simple approach work and no distinction
          between datatypes is needed.
'''

import numpy as np
from ctypes import *
import config
from numpy.lib.stride_tricks import as_strided

def setup(libpath) :
  
  ''' setup loads the object library 

    Parameters:
       libpath: FULL path to the shared library 
                f.ex if the name of the library is pylib.so
                and it is installed in "/home/barn/Bin"
                the path would be "/home/barn/Bin/pylib.so".
   
     Returns:
       reference to the shared library
       The global variable config.pylib is set to the
       address of the shared library.

  '''

  cdll.LoadLibrary(libpath)
  pylib = CDLL(libpath)

  #Initialize I/O
  pylib.LibeInit()

  config.pylib=pylib
  return pylib


# Eps interface for a  struct is via a class

# Class for 1d array of ints
class epsarray1di(Structure) :
 _fields_ = [("d", ARRAY(c_int,1)),("a",POINTER(c_int))] 

# Class for 2d array of ints
class epsarray2di(Structure) :
 _fields_ = [("d", ARRAY(c_int,2)),("a",POINTER(c_int))] 

# Class for 1d array of floats
class epsarray1df(Structure) :
 _fields_ = [("d", ARRAY(c_int,1)),("a",POINTER(c_float))] 

# Class for 2d array of floats
class epsarray2df(Structure) :
 _fields_ = [("d", ARRAY(c_int,2)),("a",POINTER(c_float))] 

# Class for strings
class epsarrays(Structure) :
 _fields_ = [("d", ARRAY(c_int,1)),("a",c_char_p)] 


def Izeros1di(pylib,dims) :
  ''' Izeros1di creates 1d int  32 bit numpy array

      Parameters :
        pylib  :  Pointer to shared lib
        dims   :  List of dimensions

      Returns:
        int  32 bit 1d array with dimensions dims.
        The data pointer is obtained from allocation
        in cpu or unified memory. 

  '''

  # Set the argument and return type of the memory allocator
  pylib.PyepsCre1di.argtypes=[c_int]
  pylib.PyepsCre1di.restype=c_void_p
  nx = dims[0]

  # Allocate memory for the eps array
  epsarr = pylib.PyepsCre1di(nx)
  dimension=(nx,)

  # Get the data  of a 1d int eps array
  data=Data1di(epsarr)

  # Cast to numpy int pointer type
  data  = cast(data, POINTER(c_int))

  # Create the numpy array using the ctypes constructor
  out = np.ctypeslib.as_array(data,shape=dimension)

  # Store the eps array in a dictionary with the
  # numpy id as key
  config.descr[id(out)]=epsarr

  # Store the numpy array in a dictionary
  # with the numpy id as a key
  config.nparr[id(out)]=out

  return(out)

def Izeros2di(pylib,dims) :
  ''' Izeros2di creates 2d int  32 bit numpy array

      Parameters :
        pylib  : Pointer to shared lib
        dims   : List of dimensions

      Returns:
        int  32 bit 2d array with dimensions dims.
        The data pointer is obtained from allocation
        in cpu or unified memory. 

  '''

  # Set the argument and return type of the memory allocator
  pylib.PyepsCre2di.argtypes=[c_int,c_int]
  pylib.PyepsCre2di.restype=c_void_p
  nx = dims[0]
  ny = dims[1]

  # Allocate memory for the eps array
  epsarr = pylib.PyepsCre2di(nx,ny)
  dimension=(nx,ny)

  # Get the data  of a 2d int eps array
  data=Data2di(epsarr)

  # Cast to numpy int pointer type
  data  = cast(data, POINTER(c_int))

  # Create the numpy array using the ctypes constructor
  out = np.ctypeslib.as_array(data,shape=dimension)

  # Map to fortran style ordering
  out = np.ndarray(dimension,dtype=np.int32,buffer=out,order='F')

  # Store the eps array in a dictionary with the
  # numpy id as key
  config.descr[id(out)]=epsarr

  # Store the numpy array in a dictionary
  # with the numpy id as a key
  config.nparr[id(out)]=out

  return(out)

def Fzeros1df(pylib,dims) :

  ''' Fzeros1df creates 1d float  32 bit numpy array

      Parameters :
        pylib  :  Pointer to shared lib
        dims   :  List of dimensions

      Returns:
        float 32 bit 1d float array with dimensions dims.
        The data pointer is obtained from allocation
        in cpu or unified memory. 

  '''

  # Set the argument and return type of the memory allocator
  config.pylib.PyepsCre1df.argtypes=[c_int]
  config.pylib.PyepsCre1df.restype=c_void_p
  nx = dims[0]

  # Allocate memory for the eps array
  epsarr = config.pylib.PyepsCre1df(nx)
  dimension=(nx,)

  # Get the data pointer from epsarr
  data=Data1df(epsarr)

  # Cast to numpy float pointer type
  data  = cast(data, POINTER(c_float))

  # Create the numpy array using the ctypes constructor
  out = np.ctypeslib.as_array(data,shape=dimension)

  # Store the eps array in a dictionary with the
  # numpy id as key
  config.descr[id(out)]=epsarr

  # Store the numpy array in a dictionary
  # with the numpy id as a key
  config.nparr[id(out)]=out

  return(out)

def Fzeros2df(pylib,dims) :

  ''' Fzeros2df creates 2d float  32 bit array

      Parameters :
        py;ib  :  Pointer to shared lib
        dims   :  List of dimensions

      Returns:
        float 32 bit 2d float array with dimensions dims.
        The data pointer is obtained from allocation
        in cpu or unified memory. 

  '''

  # Set the argument and return type of the memory allocator
  pylib.PyepsCre2df.argtypes=[c_int]
  pylib.PyepsCre2df.restype=c_void_p
  nx = dims[0]
  ny = dims[1]

  # Allocate memory for the eps array
  epsarr = pylib.PyepsCre2df(nx,ny)
  dimension=(nx,ny)

  # Get the data pointer from epsarr
  narr = cast(epsarr,POINTER(epsarray2df))
  data = (narr.contents).a

  # Create the numpy array using the ctypes constructor
  out = np.ctypeslib.as_array(data,shape=dimension)
  
  # Map to fortran style ordering
  out = np.ndarray(dimension,dtype=np.float32,buffer=out,order='F')

  # Store the eps array in a dictionary with the
  # numpy id as key
  config.descr[id(out)]=epsarr

  # Store the numpy array in a dictionary
  # with the numpy id as a key
  config.nparr[id(out)]=out

  return(out)

def Izeros(dims) :

  ''' Izeros creates int arrays

      Parameters :
        dims   :  List of dimensions

      Returns:
        float 32 bit int array with dimensions dims.

  '''

  if(len(dims) == 1):
    return Izeros1di(config.pylib,dims)
  elif(len(dims)==2):
    return Izeros2di(config.pylib,dims)
  else:
    printf("Incorrect dimensions")
    Exit()
  
def Fzeros(dims) :

  ''' Fzeros creates float arrays

      Parameters :
        dims   :  List of dimensions

      Returns:
        float 32 bit float array with dimensions dims.

  '''

  if(len(dims) == 1):
    return(Fzeros1df(config.pylib,dims))
  elif(len(dims)==2):
    return(Fzeros2df(config.pylib,dims))
  else:
    printf("Incorrect dimensions")
    Exit()
  

def Bytes(dims) :

  ''' Bytes creates a byte array

      Parameters :
        dims   :  Length of array

      Returns:
        bytearray

  '''

  return(bytearray([0]*dims))
  
def eps1di(arr):
  '''eps1di converts a 1d numpy int array to an eps array
  
      Parameters:
        arr     : 1D numpy int array
  '''
  if(arr.flags['F_CONTIGUOUS'] == False) :
    print("The numpy array is not contiguos.")
    exit()

  # Get the eps array pointer
  epsp=config.descr[id(arr)]
  return(epsp)

def num1di(arr):
  '''eps1di converts a 1d int epsarray to a numpy array
  
      Parameters:
        arr     : 1D eps int array
  '''

  # Find the id of the correponding numpy array.
  for key, value in config.descr.items():
      if value == arr:
        id = key
        break  # Exit the loop once a match is found

  # Get the array itself  
  return(config.nparr[id])

def eps2di(arr):

  '''eps2di converts a 2d numpy int array to an eps array
  
      Parameters:
        arr     : 2D numpy int array
  '''
  if(arr.flags['F_CONTIGUOUS'] == False) :
    print("The numpy array is not contiguos.")
    exit()

  # Get the eps array pointer
  epsp=config.descr[id(arr)]
  return(epsp)

def num2di(arr):

  '''num2di converts a 2d int epsarray to a numpy array
  
      Parameters:
        arr     : 2D eps int array
  '''

  # Get the id for the corresponding numpy array
  for key, value in config.descr.items():
    if value == arr:
      id = key
      break  # Exit the loop once a match is found

  # Get the array itself  
  return(config.nparr[id])
  return(out)

def eps1df(arr):

  '''eps converts a 1d numpy float array to an eps array
  
      Parameters:
        arr     : 1D numpy float array
  '''
  
  if(arr.flags['F_CONTIGUOUS'] == False) :
    print("The numpy array is not contiguos.")
    exit()

# Get the eps array pointer
  epsp=config.descr[id(arr)]
  return(epsp)

def num1df(arr):

  '''eps converts a 1d eps float array to a numpy array
  
      Parameters:
        arr     : 1D eps int array
  '''

  # Find the array id from the eps pointer
  for key, value in config.descr.items():
      if value == arr:
        id = key
        break  # Exit the loop once a match is found

  # Get the array itself  
  return(config.nparr[id])

def eps2df(arr):

  '''eps converts a 2d numpy float array to an eps array
  
      Parameters:
        arr     : 2D numpy float array
  '''

  if(arr.flags['F_CONTIGUOUS'] == False) :
    print("The numpy array is not contiguos.")
    exit()

  # Get the eps array pointer
  epsp=config.descr[id(arr)]
  return(epsp)


def num2df(arr):

  '''eps converts a 2d eps float array to a numpy array
  
      Parameters:
        arr     : 2D eps float array
  '''

  # Find the id for the corresponding numpy array
  for key, value in config.descr.items():
    if value == arr:
      id = key
      break  # Exit the loop once a match is found

  # Get the array itself
  return(config.nparr[id])
  return(out)


def eps1dc(arr):

  ''' eps1dc allocates memory and copies 1D char array into memory
  
      Parameters:
        pylib   : Shared library containg c-functions
        arr     : python string
  '''

  pylib=config.pylib

  # Set the argument and return type of the memory allocator
  pylib.PyepsCre1ds.argtypes=[c_int]
  pylib.PyepsCre1ds.restype=c_void_p
  nx = len(arr)

  # Allocate memory for the eps array
  out = pylib.PyepsCre1ds(nx) 
  
  # Fill in the eps array descriptor with
  # dimensions and data
  epsarr = epsarrays()
  epsarr.a = c_char_p(arr.encode("utf-8"))
  epsarr.d[0]=nx
  epsarrp = pointer(epsarr)

  # Set the argument types of Copy1ds
  pylib.PyepsCopy1ds.argtypes=[POINTER(epsarrays),c_void_p]
  pylib.PyepsCopy1ds.restype=c_int

  # Copy the numpy array into the eps array
  pylib.PyepsCopy1ds(epsarr,out)
  
  return(out)

def num1dc(arr):

  '''  num1dc converts a 1D eps char array into a string
  
      Parameters:
        arr     : 1D eps char array
        
      Return :
        out     : copy of input eps string array
          
  '''

  # Fill in the eps array descriptor with
  # dimensions and data
  
  narr = cast(arr,POINTER(epsarrays))
  ns = (narr.contents).d[0]
  epsarr = epsarrays()
  out=Bytes(ns)
  epsarr.a = c_char_p(bytes(out))
  epsarr.d[0]=ns
  epsarrp = pointer(epsarr)

  # Set the argument types of Copy1ds
  config.pylib.PyepsCopy1ds.argtypes=[c_void_p,POINTER(epsarrays)]
  config.pylib.PyepsCopy1ds.restype=c_int

  # Copy eps array into string
  config.pylib.PyepsCopy1ds(arr,epsarrp)
  bs=epsarrp.contents
  bss=bs.a
  return(bss.decode('utf-8'))

def Dims1di(arr):

  ''' 
  
      Parameters:
        arr           : 1D eps array
        
      Return :
        returns the length
          
  '''

  narr = cast(arr,POINTER(epsarray1di))
  nx = (narr.contents).d[0]
  return(nx,)

def Dims2di(arr):

  ''' Dims2di get the length of a 2d int array
  
      Parameters:
        arr           : 2D eps array
        
      Return :
        returns a tuple with first and second dimension
          
  '''

  narr = cast(arr,POINTER(epsarray2di))
  n1 = (narr.contents).d[0]
  n2 = (narr.contents).d[1]
  return (n1,n2)

def Dims1df(arr):

  ''' Dims1df get the length of a 1d float array
  
      Parameters:
        arr : 1D eps array
        
      Return :
        returns the length
          
  '''

  narr = cast(arr,POINTER(epsarray1df))
  nx = (narr.contents).d[0]
  return(nx,)

def Dims2df(arr):
  ''' Dims2df get the length of a 2d float array
  
      Parameters:
        arr : 2D eps array
        
      Return :
        returns a tuple with first and second dimension
          
  '''

  narr = cast(arr,POINTER(epsarray2df))
  n1 = (narr.contents).d[0]
  n2 = (narr.contents).d[1]
  return (n1,n2)


def Dims1dc(str):

  ''' Dims1dc get the length of a string
  
      Parameters:
        str : 1D eps array
        
      Return :
        returns the length of the string
          
  '''

  nstr = cast(str,POINTER(epsarrays))
  n1 = (nstr.contents).d[0]
  return (n1)

def Data1di(arr):

  ''' Data1di gets the data pointer from a 1D integer eps array 

      Parameters:
        arr  : 1D eps array
        
      Return :
        returns the data pointer
          
  '''

  narr = cast(arr,POINTER(epsarray1di))
  data = (narr.contents).a
  data = cast(data,POINTER(c_void_p))
  return(data)

def Data2di(arr):

  ''' Data2di gets the data pointer from a 2D integer eps array 
      Parameters:
        arr : 2D eps array
        
      Return :
        returns the data pointer
          
  '''

  narr = cast(arr,POINTER(epsarray2di))
  data = (narr.contents).a
  data = cast(data,POINTER(c_void_p))
  return(data)

def Data1df(arr):

  ''' Data1df gets the data pointer from a 1D float eps array 

      Parameters:
        arr  : 1D eps array
        
      Return :
        returns the data pointer
          
  '''

  narr = cast(arr,POINTER(epsarray1df))
  data = (narr.contents).a
  data = cast(data,POINTER(c_void_p))
  return(data)

def Data2df(arr):

  ''' Data2df gets the data pointer from a 2D float eps array 
      Parameters:
        arr : 2D eps array
        
      Return :
        returns the data pointer
          
  '''

  narr = cast(arr,POINTER(epsarray2df))
  data = (narr.contents).a
  data = cast(data,POINTER(c_void_p))
  return(data)

def fzeros(dims) :
    return(np.zeros(dims,dtype=np.float32,order='F'))
def izeros(dims) :
    return(np.zeros(dims,dtype=np.int32,order='F'))
